### ISSUE TITLE
Feed page

### ISSUE THREAD

**Issue by homayunmmdy** [homayunmmdy/Nexca#105]
create seprate page called feed where should list of all posts with inifite scroll use card components for the post and show the latest at the top for now  also use react query for infite query

**Comment by yacNLP** [comment]
I have submitted a Pull Request (#109) addressing this issue. Please let me know if there are any changes or improvements needed!

**Comment by homayunmmdy** [comment]
Thank you for your contribution! We’ve reviewed your changes to the feed and services pages, and everything looks great overall. However, after testing, we noticed an issue: approximately 90% of the posts on the demo page are not displaying, and the admin panel’s post list is also affected.

This issue seems to be related to changes in the get method, which might require updates to other rendering functions or adjustments to get itself. Unfortunately, I’m currently too busy to address this right away. If you’d like to work on resolving this issue, that would be great! Otherwise, I’ll revisit it when I have more time.

For now, to avoid disruption, we’ve reverted your changes. Let me know how you’d like to proceed. @yacNLP

**Comment by yacNLP** [comment]
okey, I will check that and let you know

**Comment by homayunmmdy** [comment]
thanks it is work well @yacNLP
