### ISSUE TITLE
Add comments for posts

### ISSUE THREAD

**Issue by homayunmmdy** [homayunmmdy/Nexca#91]
add commetns feature where users can enter they name email and comment and show them under that post

**Comment by SujayDas1999** [comment]
Hi @homayunmmdy 
I would like to work on this issue. You can assign it to me.

**Comment by homayunmmdy** [comment]
OK  it's assign to you @SujayDas1999

**Comment by SujayDas1999** [comment]
Will it have replies functionality ?

**Comment by homayunmmdy** [comment]
Let's start by developing the basic feature that allows users to send comments. Once that's in place, we can focus on improving it further. @SujayDas1999

**Comment by SujayDas1999** [comment]
Sounds good @homayunmmdy. Will start working on it.

**Comment by SujayDas1999** [comment]
Hi @homayunmmdy . I wanted to ask does this application stores post data somewhere? Or it is static as of now?

**Comment by homayunmmdy** [comment]
Hi , we store our data in the Mongo db but for the development I use cash for more information read this [post](https://nexca.vercel.app/posts/673b7647c8b9dd301584f384) why we use cash in dev @SujayDas1999

**Comment by SujayDas1999** [comment]
I have created a PR with a simple form. I would recommend to merge that in first. Then we can take care of saving updating and getting the comments. @homayunmmdy

**Comment by homayunmmdy** [comment]
You're right that the style of the contact form and comments might look similar, but their implementations are completely different. The contact form sends a simple API request, while the comment form needs to check the post ID, send an API request for the specific post, and store each comment in the post's comments array.

For the comment form, I also plan to refactor the theme and add validation to it. Right now, I’ve added a very simple prototype where, if you send a comment, it will display on the page. However, the data isn’t yet stored in the post’s comments array—I’ll work on that as well.

What do you think of this approach?

 @SujayDas1999

**Comment by homayunmmdy** [comment]
Thank you, @SujayDas1999 , for your valuable contributions! I'll go ahead and close this issue for now and create more specific ones for the comments as needed. Additionally, I plan to implement a reusable form where possible, considering the different structures I mentioned earlier. There are also other issues to address, so feel free to contribute further or create your own issues. I truly appreciate your help!

**Comment by SujayDas1999** [comment]
> You're right that the style of the contact form and comments might look similar, but their implementations are completely different. The contact form sends a simple API request, while the comment form needs to check the post ID, send an API request for the specific post, and store each comment in the post's comments array.
> 
> For the comment form, I also plan to refactor the theme and add validation to it. Right now, I’ve added a very simple prototype where, if you send a comment, it will display on the page. However, the data isn’t yet stored in the post’s comments array—I’ll work on that as well.
> 
> What do you think of this approach?
> 
> @SujayDas1999

Hi @homayunmmdy 

What I feel is the contact form should emit the data as an event and the parent component should be responsible to make api calls. This way we could avoid creating components with the exact same layout and same validations. 

Alternatively we could use a Hoc to transform the form component by adding new features if required.

Apologies for the late reply.

**Comment by homayunmmdy** [comment]
I've made the contact and comments forms reusable as part of issue #100. You can now see the updated version live on [Nexca](https://nexca.vercel.app/). The forms are more scalable and have better accessibility thanks to the creation of a separate API for comments. This innovative approach was inspired while watching the Billion Dollar Movie. @SujayDas1999
